### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by DLrook** [xiaojino/RUArt#3]
Hi Mr..@xiaojino
Thanks for you code.
I want to run this code , but the file I have downloaded from Huggingface -bert-base-uncased may has something wrong, there is no file named vocab.txt.
Could you know what wrong with it ? I would very appreciate it .

**Comment by xiaojino** [comment]
> bert-base-uncased

Hi，@DLrook，
Maybe you can download the right files from [Hugging Face](https://huggingface.co/bert-base-uncased/tree/main)'s website.

**Comment by DLrook** [comment]
Hi,Mr..@xiaojino
Thank you very much for your answer.
I have solved the problem.
